version: '3.9'

services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: gutenberg_restore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
